from . import res_base_abstractmodel
from . import sick_persion_info
from . import examine_history_info
from . import payment_history
from . import medicine_info
from . import doctor_info
from . import schedule_examine
from . import master_data
from . import res_company
from . import special_customer
from . import potential_patient
